DomainGroupPagesTypes:
    type: object
    config:
        fields:
            landingPage:
                type: LandingPageContentType
                resolve: '@=resolver("ContentType", [{"identifier": "landing_page"}])'
