GalleryPageBlock:
    type: object
    inherits:
        - BasePageBlock
    config:
        fields:
            contentId:
                type: DomainContent
                resolve: '@=resolver("EmbedAttributeValue", [value.getAttribute("contentId").getValue()])'
