ProductListContent:
    type: object
    inherits:
        - AbstractDomainContent
    config:
        interfaces:
            - DomainContent
            - Node
        fields:
            title:
                type: String
                resolve: '@=resolver("DomainFieldValue", [value, "title"])'
            shortTitle:
                type: String
                resolve: '@=resolver("DomainFieldValue", [value, "short_title"])'
            banner:
                type: ImageFieldValue
                resolve: '@=resolver("DomainFieldValue", [value, "banner"])'
            description:
                type: RichTextFieldValue
                resolve: '@=resolver("DomainFieldValue", [value, "description"])'
            metas:
                type: String
                resolve: '@=resolver("DomainFieldValue", [value, "metas"])'
