RichtextPageBlockViews:
    type: enum
    config:
        values:
            default:
                value: '@EzPlatformPageFieldType/blocks/richtext.html.twig'
                description: 'Default view'
