RssPageBlockViews:
    type: enum
    config:
        values:
            list:
                value: '@ezdesign/blocks/rss/list.html.twig'
                description: List
            default:
                value: '@EzPlatformPageFieldType/blocks/rss.html.twig'
                description: 'Default block layout'
