services:
    AppBundle\Event\Subscriber\BuildDemoSchemaSubscriber:
        autoconfigure: true
        arguments:
            - '@=service("kernel").locateResource("@AppBundle/Resources/schema/demo.yaml")'

    app.installer.ee-demo_installer:
        autowire: true
        parent: ezplatform.installer.db_based_installer
        class: AppBundle\Installer\PlatformEEDemoInstaller
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
        tags:
            - { name: ezplatform.installer, type: ezplatform-ee-demo }

    app.installer.demo-test-layouts_installer:
        parent: ezplatform.installer.db_based_installer
        class: AppBundle\Installer\PlatformEEDemoTestLayoutsInstaller
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
        tags:
            - { name: ezplatform.installer, type: demo-test-layouts }
