ezplatform_page_fieldtype:
    layouts:
        '1':
            identifier: '1'
            name: '1 column'
            description: '1 column'
            thumbnail: '/assets/images/page_builder/layouts/1.png'
            template: '@ezdesign/layouts/1.html.twig'
            zones:
                first:
                    name: 'First zone'

        '1_2':
            identifier: '1_2'
            name: '2 columns'
            description: '2 columns'
            thumbnail: '/assets/images/page_builder/layouts/1_2.png'
            template: '@ezdesign/layouts/1_2.html.twig'
            zones:
                first:
                    name: 'First zone'
                second:
                    name: 'Second zone'

        '2_1':
            identifier: '2_1'
            name: '2 columns'
            description: '2 columns'
            thumbnail: '/assets/images/page_builder/layouts/2_1.png'
            template: '@ezdesign/layouts/2_1.html.twig'
            zones:
                first:
                    name: 'First zone'
                second:
                    name: 'Second zone'

        '1__1_2':
            identifier: '1__1_2'
            name: '2 columns, wide top'
            description: '2 columns, wide top'
            thumbnail: '/assets/images/page_builder/layouts/1__1_2.png'
            template: '@ezdesign/layouts/1__1_2.html.twig'
            zones:
                first:
                    name: 'First zone'
                second:
                    name: 'Second zone'
                third:
                    name: 'Third zone'

        '1__2_1':
            identifier: '1__2_1'
            name: '2 columns, wide top'
            description: '2 columns, wide top'
            thumbnail: '/assets/images/page_builder/layouts/1__2_1.png'
            template: '@ezdesign/layouts/1__2_1.html.twig'
            zones:
                first:
                    name: 'First zone'
                second:
                    name: 'Second zone'
                third:
                    name: 'Third zone'

        '1w__1__1w':
            identifier: '1w__1__1w'
            name: '3 Zone, 1 Column'
            description: '1 column, 3 zones'
            thumbnail: '/assets/images/page_builder/layouts/1w__1__1w.png'
            template: '@ezdesign/layouts/1w__1__1w.html.twig'
            zones:
                first:
                    name: 'First wide zone'
                second:
                    name: 'Second zone'
                third:
                    name: 'Third wide zone'

        '1w__2_1__2_1__1w':
            identifier: '1w__2_1__2_1__1w'
            name: 'Mixed columns, 6 Zones'
            description: 'Mixed columns, 6 Zones'
            thumbnail: '/assets/images/page_builder/layouts/1w__2_1__2_1__1w.png'
            template: '@ezdesign/layouts/1w__2_1__2_1__1w.html.twig'
            zones:
                top:
                    name: 'Top wide zone'
                topleft:
                    name: 'Top left inner grid zone'
                topright:
                    name: 'Top right inner grid zone'
                bottomleft:
                    name: 'Bottom left inner grid zone'
                bottomright:
                    name: 'Bottom right inner grid zone'
                bottom:
                    name: 'Bottom wide zone'

        'test_layout':
            identifier: 'test_layout'
            name: 'Test Layout'
            description: 'Test layout - all possible zones'
            thumbnail: '/assets/images/page_builder/layouts/test.png'
            template: '@ezdesign/layouts/test_layout.html.twig'
            zones:
                wide:
                    name: 'Wide zone'
                standard:
                    name: 'Standard zone'
                col_12:
                    name: 'col-12 zone'
                'col_4_1':
                    name: 'col-4 first zone'
                'col_8_2':
                    name: 'col-8 second zone'
                'col_6_1':
                    name: 'col-6 first zone'
                'col_6_2':
                    name: 'col-6 second zone'
                default_no_bs:
                    name: 'Default zone - no bootstrap'
                grid_1:
                    name: 'Grid zone 1'
                grid_2:
                    name: 'Grid zone 2'
                grid_3:
                    name: 'Grid zone 3'
                grid_4:
                    name: 'Grid zone 4'

    blocks:
        hero:
            views:
                default:
                    template: '@ezdesign/blocks/hero/default.html.twig'
                    name: 'Hero'

        contentlist:
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#contentlist'
            views:
                cards:
                    template: '@ezdesign/blocks/contentlist/cards.html.twig'
                    name: 'Cards'

                list:
                    template: '@ezdesign/blocks/contentlist/list.html.twig'
                    name: 'List'

                blog:
                    template: '@ezdesign/blocks/contentlist/blog.html.twig'
                    name: 'Blog'

        banner:
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#banner'
            views:
                banner:
                    template: '@ezdesign/blocks/banner/banner.html.twig'
                    name: 'Banner'

        embed:
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#embed'
            views:
                embed:
                    template: '@ezdesign/blocks/embed/embed.html.twig'
                    name: 'Hero'

                embed_wide:
                    template: '@ezdesign/blocks/embed/embed_wide.html.twig'
                    name: 'Wide'

        places:
            views:
                map:
                    template: '@ezdesign/blocks/places/map.html.twig'
                    name: 'Map'

                cards:
                    template: '@ezdesign/blocks/places/cards.html.twig'
                    name: 'Cards'

                list:
                    template: '@ezdesign/blocks/places/list.html.twig'
                    name: 'List'
        tastes:
            views:
                cards:
                    template: '@ezdesign/blocks/tastes/cards.html.twig'
                    name: 'Cards'

                list:
                    template: '@ezdesign/blocks/tastes/list.html.twig'
                    name: 'List'

                home:
                    template: '@ezdesign/blocks/tastes/home.html.twig'
                    name: 'Home page'

        gallery:
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#gallery'
            views:
                gallery:
                    template: '@ezdesign/blocks/gallery/gallery.html.twig'
                    name: 'Gallery'

        rss:
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#rss'
            views:
                list:
                    template: '@ezdesign/blocks/rss/list.html.twig'
                    name: 'List'

        video:
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#video'
            views:
                player:
                    template: '@ezdesign/blocks/video/player.html.twig'
                    name: 'Player'

        collection:
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#collection'
            views:
                cards:
                    template: '@ezdesign/blocks/collection/cards.html.twig'
                    name: 'Cards'
                    options:
                        match: [article, blog_post, image, product, place]

                list:
                    template: '@ezdesign/blocks/collection/list.html.twig'
                    name: 'List'
                    options:
                        match: [article, blog_post, image, product, place]

        schedule:
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#schedule'
            views:
                cards:
                    template: '@ezdesign/blocks/schedule/cards.html.twig'
                    name: 'Cards'

                list:
                    template: '@ezdesign/blocks/schedule/list.html.twig'
                    name: 'List'

        tag:
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#tag'

        richtext:
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#paragraph'

        personalized:
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#personalize-block'
            views:
                cards:
                    template: '@ezdesign/blocks/personalized/cards.html.twig'
                    name: 'Cards'

                list:
                    template: '@ezdesign/blocks/personalized/list.html.twig'
                    name: 'List'
