app.submitted:
    path: /contact/submitted
    defaults:
        _controller: app.controller.contactform:submittedAction
        template: "@ezdesign/full/contact_form_submitted.html.twig"
    methods: [GET]

# Custom redirection from /ez to /admin, feel free to adjust to your needs or remove if you don't need it
platform1_admin_route:
    path: /ez
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin
        permanent: true

