# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html

imports:
    - { resource: services/controllers.yml }

parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    app.query_type.menu:
        class: AppBundle\QueryType\MenuQueryType
        calls:
            - [setLanguages, [$languages$]]
        tags:
            - { name: ezpublish.query_type }

    app.mail.sender:
        class: AppBundle\Mail\Sender
        public: true
        arguments:
            - '@mailer'
            - '@translator'
            - '@templating'
            - '%app.contact_form.sender_email%'
            - '%app.contact_form.recipient_email%'

    app.twig.content_info_by_location_id_extension:
        class: AppBundle\Twig\ContentInfoByLocationIdExtension
        arguments:
            - '@ezpublish.api.service.location'
            - '@ezpublish.api.service.content'

    AppBundle\Twig\YoutubeIdExtractorExtension:
        tags:
            - { name: twig.extension }

    AppBundle\QueryType\BlockQueryType: ~

    AppBundle\Event\Subscriber\PlacesBlockSubscriber:
        arguments:
            $queryType: '@AppBundle\QueryType\BlockQueryType'

    AppBundle\Event\Subscriber\TastesBlockSubscriber:
        arguments:
            $queryType: '@AppBundle\QueryType\BlockQueryType'

    AppBundle\Twig\SearchResultExtractorExtension:
        tags:
            - { name: twig.extension }

    AppBundle\PremiumContent\HtmlRenderer: ~
    AppBundle\User\UserGroups: ~

    AppBundle\Twig\PremiumContentExtension:
        arguments:
            - '@AppBundle\PremiumContent\HtmlRenderer'
            - '@AppBundle\User\UserGroups'
            - '%app.premium_content.allowed_user_groups.location_ids%'
        tags:
            - { name: twig.extension }

    AppBundle\Twig\ContentDescriptionExtension:
        arguments:
        - "@ezpublish.field_helper"
        - "@?logger"
        tags:
            - { name: twig.extension }

    AppBundle\Event\TemplateAttributeBlockNameListener:
        tags:
            - { name: kernel.event_subscriber }

    AppBundle\Event\PageFieldType\Attribute\AttributeSerializationSubscriber: ~

    AppBundle\Event\Listener\RenderMenuListener:
        arguments:
            $credentialsChecker: '@EzSystems\EzRecommendationClient\Config\EzRecommendationClientCredentialsChecker'
        tags:
            - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: renderMenu, priority: -45 }

    AppBundle\Event\Workflow\PublishOnLastStageSubscriber:
        arguments:
            $publishOnLastStageWorkflows: '%app.workflow.publish_on_last_stage%'

    AppBundle\Event\Subscriber\EndWorkflowSubscriber: ~

    AppBundle\Event\Subscriber\Recommendation\UserCollectionSubscriber:
        arguments:
            $membersUserGroupId: '%app.members_user_group_id%'
