ezpublish:
    system:
        site_group:
            pagelayout: "@ezdesign/pagelayout.html.twig"

            field_templates:
                - {template: "@ezdesign/fields/eztags_field.html.twig", priority: 20}
                - {template: '@ezdesign/fields/ezform_field.html.twig', priority: 30}

            user:
                layout: "@ezdesign/pagelayout.html.twig"
                login_template: "@ezdesign/user/login.html.twig"

            user_registration:
                templates:
                    form: "@ezdesign/user/registration_form.html.twig"
                    confirmation: "@ezdesign/user/registration_confirmation.html.twig"

            content_view:
                full:
                    home:
                        template: "@ezdesign/full/home.html.twig"
                        params:
                            place_list_location_id: '%app.home.place_list_location_id%'
                            tastes_location_id: '%app.home.tastes_location_id%'
                        match:
                            Id\Location: 2
                            Identifier\ContentType: [folder]

                    article:
                        template: "@ezdesign/full/article.html.twig"
                        match:
                            Identifier\ContentType: [article]

                    folder:
                        controller: "ez_query:contentQueryAction"
                        template: "@ezdesign/full/folder.html.twig"
                        match:
                            Identifier\ContentType: [folder]
                        params:
                            query:
                                query_type: "AppBundle:Children"
                                parameters:
                                    parent_location_id: "@=location.id"
                                assign_results_to: children

                    place:
                        template: "@ezdesign/full/place.html.twig"
                        match:
                            Identifier\ContentType: [place]

                    place_list:
                        controller: "ez_query:contentQueryAction"
                        template: "@ezdesign/full/place_list.html.twig"
                        match:
                            Identifier\ContentType: [place_list]
                        params:
                            query:
                                query_type: "AppBundle:Children"
                                parameters:
                                    parent_location_id: "@=location.id"
                                assign_results_to: places

                    blog:
                        controller: "ez_query:contentQueryAction"
                        template: "@ezdesign/full/blog.html.twig"
                        match:
                            Identifier\ContentType: [blog]
                        params:
                            query:
                                query_type: "AppBundle:Children"
                                parameters:
                                    parent_location_id: "@=location.id"
                                assign_results_to: children

                    blog_post:
                        template: "@ezdesign/full/blog_post.html.twig"
                        match:
                            Identifier\ContentType: [blog_post]

                    subscribe:
                        controller: app.controller.contactform:showContactFormAction
                        template: "@ezdesign/full/subscribe.html.twig"
                        match:
                            Identifier\ContentType: [subscribe]

                    about:
                        template: "@ezdesign/full/about.html.twig"
                        match:
                            Identifier\ContentType: [about]

                    product:
                        template: "@ezdesign/full/product.html.twig"
                        match:
                            Identifier\ContentType: [product]

                    product_list:
                        controller: "app.controller.product_list_controller:contentQueryPaginationAction"
                        params:
                            page_limit: 12
                            view_type: card
                            query:
                                query_type: "AppBundle:Children"
                                parameters:
                                    parent_location_id: '@=location.id'
                                    included_content_type_identifier: 'product'
                                assign_results_to: children
                        template: "@ezdesign/full/product_list.html.twig"
                        match:
                            Identifier\ContentType: [product_list]

                    form:
                        template: "@ezdesign/full/form.html.twig"
                        match:
                            Identifier\ContentType: [form]

                    landing_page:
                        template: "@ezdesign/full/landing_page.html.twig"
                        match:
                            Identifier\ContentType: "landing_page"

                home:
                    place_list:
                        controller: 'ez_query:ContentQueryAction'
                        template: '@ezdesign/home/place_list.html.twig'
                        params:
                            query:
                                query_type: 'AppBundle:Children'
                                parameters:
                                    limit: 3
                                    parent_location_id: '@=location.id'
                                    included_content_type_identifier: 'place'
                                assign_results_to: places
                        match:
                            Identifier\ContentType: [place_list]

                    tastes:
                        controller: 'ez_query:ContentQueryAction'
                        template: '@ezdesign/home/tastes.html.twig'
                        params:
                            query:
                                query_type: 'AppBundle:Children'
                                parameters:
                                    limit: 3
                                    parent_location_id: '@=location.id'
                                    included_content_type_identifier: 'article'
                                assign_results_to: tastes
                        match:
                            Identifier\ContentType: [folder]

                embed:
                    home_tastes:
                        template: "@ezdesign/embed/home_tastes.html.twig"
                        match:
                            Identifier\ContentType: [article]

                line:
                    blog_post:
                        template: "@ezdesign/line/blog_post.html.twig"
                        match:
                            Identifier\ContentType: [blog_post]

                card:
                    article:
                        template: "@ezdesign/card/article.html.twig"
                        match:
                            Identifier\ContentType: [article]

                    place:
                        template: "@ezdesign/card/place.html.twig"
                        match:
                            Identifier\ContentType: [place]

                    product:
                        template: "@ezdesign/card/product.html.twig"
                        match:
                            Identifier\ContentType: [product]
                    default:
                        template: "@ezdesign/default/default.html.twig"
                        match:
                            Identifier\ContentType: [form, folder, gallery, image, landing_page]

                featured:
                    article:
                        template: "@ezdesign/featured/article.html.twig"
                        match:
                            Identifier\ContentType: [article]

                search_result_item:
                    article:
                        template: "@ezdesign/search_result_item/article.html.twig"
                        match:
                            Identifier\ContentType: [article]
                    place:
                        template: "@ezdesign/search_result_item/place.html.twig"
                        match:
                            Identifier\ContentType: [place]
                    product:
                        template: "@ezdesign/search_result_item/product.html.twig"
                        match:
                            Identifier\ContentType: [product]
                    blog_post:
                        template: "@ezdesign/search_result_item/default.html.twig"
                        match:
                            Identifier\ContentType: [blog_post]
                    default:
                        template: "@ezdesign/search_result_item/default.html.twig"
                        match:
                            Identifier\ContentType: [image, blog, folder, place_list, video, article, place, product, blog_post]

                block_item:
                    article:
                        template: "@ezdesign/block_item/article/default.html.twig"
                        match:
                            Identifier\ContentType: [article]
                    place:
                        template: "@ezdesign/block_item/place/default.html.twig"
                        match:
                            Identifier\ContentType: [place]
                    blog_post:
                        template: "@ezdesign/block_item/blog_post/default.html.twig"
                        match:
                            Identifier\ContentType: [blog_post]
                    image:
                        template: "@ezdesign/block_item/image/default.html.twig"
                        match:
                            Identifier\ContentType: [image]
                    folder:
                        template: "@ezdesign/block_item/folder/default.html.twig"
                        match:
                            Identifier\ContentType: [folder]
                    place_list:
                        template: "@ezdesign/block_item/place_list/default.html.twig"
                        match:
                            Identifier\ContentType: [place_list]
                    video:
                        template: "@ezdesign/block_item/video/default.html.twig"
                        match:
                            Identifier\ContentType: [video]
                    product:
                        template: "@ezdesign/block_item/product/default.html.twig"
                        match:
                            Identifier\ContentType: [product]
                    product_list:
                        template: "@ezdesign/block_item/product_list/default.html.twig"
                        match:
                            Identifier\ContentType: [product_list]
                    default:
                        template: "@ezdesign/default/default.html.twig"
                        match:
                            Identifier\ContentType: [landing_page, blog, frontpage, about, user, user_group]

                block_item_card:
                    default:
                        template: "@ezdesign/block_item/card/default.html.twig"
                        match:
                            Identifier\ContentType: [product, article, blog_post, article, place, product_list, image, blog, place_list, folder, file, video, about, subscribe, gallery, form, user, user_group, landing_page]

                block_item_list:
                    default:
                        template: "@ezdesign/block_item/list/default.html.twig"
                        match:
                            Identifier\ContentType: [product, article, blog_post, article, place, product_list, image, blog, place_list, folder, file, video, about, subscribe, gallery, form, user, user_group, landing_page]

                block_item_wide:
                    blog_post:
                        template: "@ezdesign/block_item/blog_post/wide.html.twig"
                        match:
                            Identifier\ContentType: [blog_post]
                    image:
                        template: "@ezdesign/block_item/image/wide.html.twig"
                        match:
                            Identifier\ContentType: [image]
                    place:
                        template: "@ezdesign/block_item/place/wide.html.twig"
                        match:
                            Identifier\ContentType: [place]
                    product:
                        template: "@ezdesign/block_item/product/wide.html.twig"
                        match:
                            Identifier\ContentType: [product]
                    product_list:
                        template: "@ezdesign/block_item/product_list/wide.html.twig"
                        match:
                            Identifier\ContentType: [product_list]
                    default:
                        template: "@ezdesign/default/default.html.twig"
                        match:
                            Identifier\ContentType: [landing_page, blog, frontpage, about, article]

                block_item_hero:
                    default:
                        template: "@ezdesign/block_item/hero/default.html.twig"
                        match:
                            Identifier\ContentType: [landing_page, blog, about, article, blog_post, image, place]
